### PR TITLE
Use the new Rails enum API

### PR DESCRIPTION
**Pull request by ghiculescu**
https://github.com/rails/rails/pull/50987

### CODE REVIEW

**Review by rosa — APPROVED** [review]
🙏 🙌

**Comment by rosa** [comment]
I think we need to require Rails 7+ for this one 🤔 I think this was compatible with Rails < 7 before, but I think it's fine to have that requirement. We should make it explicit, though.

**Comment by ghiculescu** [comment]
Do you want me to update the gemspec in this PR?

**Comment by rosa** [comment]
Would you mind? I think that'd be perfect 🙏

**Comment by ghiculescu** [comment]
@rosa audits1984 depends on console1984, which has a development dependency on Rails: https://github.com/basecamp/console1984/blob/f0f2efd489b94be8bbc9bcfb6bff778be3885d78/console1984.gemspec#L31

Would you consider updating to be a regular dependency instead? I think that would be cleaner.

**Comment by rosa** [comment]
Ohh, I hadn't realised, thanks @ghiculescu. Yeah, that sounds good and cleaner to me 👍

**Comment by ghiculescu** [comment]
I'll leave that one to you if that's okay!

**Comment by rosa** [comment]
Of course! Done in https://github.com/basecamp/console1984/pull/105

**Comment by ghiculescu** [comment]
thanks @rosa !

**Comment by olivier-thatch** [comment]
@rosa @jorgemanrubia Any chance you could release a new version that includes this change? We're preparing for Rails 7.2 and this change would get rid of a deprecation warning that appears repeatedly when we run our test suite and in a few other places.

**Comment by jorgemanrubia** [comment]
I just released 0.7.1 @olivier-thatch! Thanks for the heads up.

**Pull request merged**
