### PR TITLE
Fix test suite and CI

### PR DESCRIPTION
**Pull request by olivier-thatch**
While working on #51, I realized the test suite was not working, so I figured I'd fix it... It turned out to be a bit more work than I anticipated 😅 

~The biggest change is using [combustion](https://github.com/pat/combustion) to test the Audits1984 Rails engine without needing a full Rails app.~

I also switched the browser driver from Selenium to [Cuprite](https://github.com/rubycdp/cuprite) for system tests.

@jorgemanrubia Let me know what you think. Happy to incorporate any feedback!

### CODE REVIEW

**Comment by northeastprince** [comment]
@olivier-thatch why should Cuprite be used?

**Comment by olivier-thatch** [comment]
> @olivier-thatch why should Cuprite be used?

It's faster and has some nice features like the ability to slow down tests (to view what's happening in non-headless mode), use remote debugging, or raise JS errors as Ruby errors. I haven't enabled any of those here to keep things simple, but I could do so based on the presence of environment variables.

**Review by jorgemanrubia — COMMENTED** [review]
@olivier-thatch thanks a lot for working on this 🙏 .

I prefer to stay with the vanilla way of testing the engine. `combustion` looks great but it's a new major dependency and [I'm wary of those](https://www.jorgemanrubia.com/2018/03/15/mind-your-dependencies/) unless they are really justified.

I do love the rest of changes though. I you remove the combustion changes I'll merge.

**Comment by olivier-thatch** [comment]
@jorgemanrubia Done!

**Review by jorgemanrubia — APPROVED** [review]
Thanks a lot @olivier-thatch 🙏

**Pull request merged**
